# Generated by Django 4.1 on 2024-05-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[], max_length=255)),
                ('city', models.CharField(choices=[], max_length=255)),
                ('village', models.CharField(choices=[], max_length=255, null=True)),
                ('street', models.CharField(choices=[], max_length=255, null=True)),
                ('contact', models.CharField(max_length=13)),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('product_name', models.CharField(max_length=255)),
                ('product_id', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=13)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
