# Generated by Django 4.1.7 on 2024-05-25 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_pick_alter_agent_city_alter_agent_region_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pick',
            name='order_no',
        ),
        migrations.AddField(
            model_name='pick',
            name='agent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='delivery.agent'),
        ),
    ]
